/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/progress`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/games/colors`; params?: Router.UnknownInputParams; } | { pathname: `/games/counting`; params?: Router.UnknownInputParams; } | { pathname: `/games`; params?: Router.UnknownInputParams; } | { pathname: `/games/memory`; params?: Router.UnknownInputParams; } | { pathname: `/games/rhyme`; params?: Router.UnknownInputParams; } | { pathname: `/games/speak-to-pass`; params?: Router.UnknownInputParams; } | { pathname: `/games/word-fill`; params?: Router.UnknownInputParams; } | { pathname: `/levels`; params?: Router.UnknownInputParams; } | { pathname: `/levels/[levelId]`, params: Router.UnknownInputParams & { levelId: string | number; } } | { pathname: `/practice/[levelId]`, params: Router.UnknownInputParams & { levelId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/progress`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/games/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/games/counting`; params?: Router.UnknownOutputParams; } | { pathname: `/games`; params?: Router.UnknownOutputParams; } | { pathname: `/games/memory`; params?: Router.UnknownOutputParams; } | { pathname: `/games/rhyme`; params?: Router.UnknownOutputParams; } | { pathname: `/games/speak-to-pass`; params?: Router.UnknownOutputParams; } | { pathname: `/games/word-fill`; params?: Router.UnknownOutputParams; } | { pathname: `/levels`; params?: Router.UnknownOutputParams; } | { pathname: `/levels/[levelId]`, params: Router.UnknownOutputParams & { levelId: string; } } | { pathname: `/practice/[levelId]`, params: Router.UnknownOutputParams & { levelId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/progress${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/games/colors${`?${string}` | `#${string}` | ''}` | `/games/counting${`?${string}` | `#${string}` | ''}` | `/games${`?${string}` | `#${string}` | ''}` | `/games/memory${`?${string}` | `#${string}` | ''}` | `/games/rhyme${`?${string}` | `#${string}` | ''}` | `/games/speak-to-pass${`?${string}` | `#${string}` | ''}` | `/games/word-fill${`?${string}` | `#${string}` | ''}` | `/levels${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/progress`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/games/colors`; params?: Router.UnknownInputParams; } | { pathname: `/games/counting`; params?: Router.UnknownInputParams; } | { pathname: `/games`; params?: Router.UnknownInputParams; } | { pathname: `/games/memory`; params?: Router.UnknownInputParams; } | { pathname: `/games/rhyme`; params?: Router.UnknownInputParams; } | { pathname: `/games/speak-to-pass`; params?: Router.UnknownInputParams; } | { pathname: `/games/word-fill`; params?: Router.UnknownInputParams; } | { pathname: `/levels`; params?: Router.UnknownInputParams; } | `/levels/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/practice/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/levels/[levelId]`, params: Router.UnknownInputParams & { levelId: string | number; } } | { pathname: `/practice/[levelId]`, params: Router.UnknownInputParams & { levelId: string | number; } };
    }
  }
}
